[package]
name = "xr"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
openxr.workspace = true
bytemuck.workspace = true
vm = { path = "../vm" }
gpu = { path = "../gpu" }